# Docker Engine - Community
# Version:           19.03.5
# 测试demo版(单容器),lpgyouxi 制作
version: '3'
services:
  php74-1215:
    container_name: php7-chengla-72
    build: ../cnp7
    networks:
    - app_net
    ports:
#    - "9001:9000"
    - "80:80"  # 本地8080映射容器80
    - "443:443"  # 本地8080映射容器80
    volumes:
    # 测试文件
#    - ../www:/var/www/html  # 挂载项目资源目录,将项目代码挂载在指定路径下，当然如果要定制PHP配置，可以像nginx一样将配置文件挂载进来
    - /你的本地代码目录/chengla:/var/www/html
    - ../cnp7/conf/nginx.conf:/etc/nginx/nginx.conf
    - ../cnp7/sites-enable:/etc/nginx/sites-enable
    - ../cnp7/sites-module:/etc/nginx/sites-module

    - ../log:/var/log/nginx
    links:
    - "redis-default:redis"




# 常规默认
  redis-default:
    container_name: redis-chengla
    build: ../redis
    networks:
    - app_net
#    - app_net
    command:
      /bin/bash -c "redis-server --port 6379 --requirepass 123456  --databases 128 --appendonly yes"
    ports:
    - 6390:6379


networks:
  myhost:
    driver: host
  app_net:
    ipam:
      driver: default
      config:
      - subnet: "172.24.79.1/24"


#172.23.79.202
